Library.Web/Controllers/BookMvcController.cs
using System.Web.Mvc;
namespace Library.Web.Controllers
{
    public class BookMvcController : Controller
    {
        public ActionResult Books()
        {
            return View("Books");
        }
        public ActionResult Authors()
        {
            return View("Authors");
        }
        public ActionResult Journals()
        {
            return View("Journals");
        }
        public ActionResult Articles()
        {
            return View("Articles");
        }
    }
}

Library.Web/Views/BookMvc/Articles.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="example" class="k-content">
    <div id="tabStrip">
        <ul>
            <li>
                @Html.ActionLink("Books", "Books", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Authors", "Authors", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Journals", "Journals", "BookMvc")
            </li>
            <li class="k-state-active">
                @Html.ActionLink("Articles", "Articles", "BookMvc")
            </li>
        </ul>
        <div id="articlesGrid">   </div>
    </div>
</div>

Library.Web/Views/BookMvc/Authors.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="example" class="k-content">
    <div id="tabStrip">
        <ul>
            <li>
                @Html.ActionLink("Books", "Books", "BookMvc")
            </li>
            <li class="k-state-active">
                @Html.ActionLink("Authors", "Authors", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Journals", "Journals", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Articles", "Articles", "BookMvc")
            </li>
        </ul>
        <div id="authorsMainGrid">   </div>
    </div>
</div>

Library.Web/Views/BookMvc/Books.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="example">
    <div id="tabStrip" kendo-tab-strip">
        <ul>
            <li class="k-state-active">
                @Html.ActionLink("Books", "Books", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Authors", "Authors", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Journals", "Journals", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Articles", "Articles", "BookMvc")
            </li>
        </ul>
            <div kendo-grid id="grid" k-options="booksGrid">
                <app-root>Загрузка...</app-root>
            </div>
    </div>
</div>

Library.Web/Views/BookMvc/Journals.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="example" class="k-content">
    <div id="tabStrip">
        <ul>
            <li>
                @Html.ActionLink("Books", "Books", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Authors", "Authors", "BookMvc")
            </li>
            <li class="k-state-active">
                @Html.ActionLink("Journals", "Journals", "BookMvc")
            </li>
            <li>
                @Html.ActionLink("Articles", "Articles", "BookMvc")
            </li>
        </ul>
        <div id="journalsGrid">   </div>
    </div>
</div>